# docker-compose.yml
version: '3.3'

services:

  web:
    build: .
    restart: always
    container_name: 'simple_image_upload_web'
    command: gunicorn simple_image_upload.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media

volumes:

  static_volume:
  media_volume:
