# Generated by Django 3.2.6 on 2021-09-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myimage',
            old_name='image',
            new_name='file',
        ),
    ]
